### ISSUE TITLE
Header file not installed on Windows?

### ISSUE THREAD

**Issue by wolfv** [conda-forge/giflib-feedstock#29]
I think the Windows package is missing the gif_lib.h file in the include folder. I checked the latest available release for Windows (which also seems to lag behind) and it didn't include the `Library/include` folder and neither the gif_lib.h file. Any reason for that?

**Comment by ocefpaf** [comment]
>  Any reason for that?

Nope. Probably the new build script is not copying it. Do you want to send a PR?

**Comment by wolfv** [comment]
Working on it... the new build script isn't even building Windows :)
